apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.serviceWebPort.port }}
      targetPort: {{ .Values.serviceWebPort.port }}
      protocol: TCP
      name: {{ .Values.serviceWebPort.name }}
    - port: {{ .Values.serviceConnectPort.port }}
      targetPort: {{ .Values.serviceConnectPort.port }}
      protocol: TCP
      name: {{ .Values.serviceConnectPort.name }}
  selector:
    {{- include "rabbitmq.selectorLabels" . | nindent 4 }}
